// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2JYo-UFsJHiHltuC1Zyaku1Ts66KFOY',
    appId: '1:1002479977757:web:41486a618573dc77654df4',
    messagingSenderId: '1002479977757',
    projectId: 'socio-torcedor-de-verdade',
    authDomain: 'socio-torcedor-de-verdade.firebaseapp.com',
    storageBucket: 'socio-torcedor-de-verdade.appspot.com',
    measurementId: 'G-YZ9J96YH2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn5HaU89yLs8O7rXq97GD76quCjifoAJc',
    appId: '1:1002479977757:android:233edb2ed93d1019654df4',
    messagingSenderId: '1002479977757',
    projectId: 'socio-torcedor-de-verdade',
    storageBucket: 'socio-torcedor-de-verdade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOteEMXBX3Zt77t3VMUke_LJfK56trO68',
    appId: '1:1002479977757:ios:d57409bfaa570a7c654df4',
    messagingSenderId: '1002479977757',
    projectId: 'socio-torcedor-de-verdade',
    storageBucket: 'socio-torcedor-de-verdade.appspot.com',
    iosClientId: '1002479977757-vt77ogl2afshivstdbhdg4vf04b20b6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.socioTorcedorFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOteEMXBX3Zt77t3VMUke_LJfK56trO68',
    appId: '1:1002479977757:ios:d57409bfaa570a7c654df4',
    messagingSenderId: '1002479977757',
    projectId: 'socio-torcedor-de-verdade',
    storageBucket: 'socio-torcedor-de-verdade.appspot.com',
    iosClientId: '1002479977757-vt77ogl2afshivstdbhdg4vf04b20b6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.socioTorcedorFront',
  );
}
